
POST   http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username" : "tuankiet1",
    "password" : "tuankiet1"
}

###
GET http://localhost:5000/api/auth/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjM5YWJlZGY2ZDBhOWU1ZDhhZTAwYjkiLCJpYXQiOjE3MTUzMTA4MzV9.ZiuvBuQ1NB-o39l5map5Per2nRlwzUuo-ux_7RZcQwc

###
POST   http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username" : "thanhhoa",
    "password" : "thanhhoa"
}

###
POST   http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username" : "tuan",
    "password" : "tuan"
}

###
POST   http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username" : "thanhhoa",
    "password" : "thanhhoa"
}

###
POST  http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjM5YWMyYWY2ZDBhOWU1ZDhhZTAwYmQiLCJpYXQiOjE3MTUzMTA4ODZ9.YLIfzSX6fonGbtjBn-xxWbbgilFKWvDF7EHrz-nSmLU

{
    "title": "React-Boostrap",
    "description": "react-bosstraps",
    "url" : "boostrap.com",
    "status": "LEARNED"
}

###
POST  http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjM5YWMyYWY2ZDBhOWU1ZDhhZTAwYmQiLCJpYXQiOjE3MTUzMTA4ODZ9.YLIfzSX6fonGbtjBn-xxWbbgilFKWvDF7EHrz-nSmLU

{
    "title": "Tri Tue Nhan Tao",
    "description": "tri tue nhan tao",
    "url" : "https://trituenhantao.com",
    "status": "TO LEARN"
}

###
GET http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmYyZGNkYjM2MTgzMGZkY2NiZjc4MWYiLCJpYXQiOjE3MjcxOTIzODN9.5pDJzqFFpYz6NsDSjrRFQv2KBwBXLn2l9N2oVJKqxrk


###
GET http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNlZDJmNjM4MDRhMTA4NmM4MTUzMzAiLCJpYXQiOjE2MzE1MTMyMDd9.VfRxyO_V7zSfLoLATEcWS2qF5hAErh-7taj87AnHcCQ


###
PUT  http://localhost:5000/api/posts/66f2dcea361830fdccbf7823
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmYyZGNkYjM2MTgzMGZkY2NiZjc4MWYiLCJpYXQiOjE3MjcxOTI2NzR9.y5m6XuTx8qZ8Glbt3oG60eTYgXvxyLdX7gSk7AAgiAg

{
    "title": "Mang May Tinh",
    "description": "mang may tinh",
    "url" : "https://fit.iuh.com",
    "status": "LEARNED"
}


6141d1c967b64cddebb947ac
6141d25867b64cddebb947b6
6141d37b67b64cddebb947ce
6141d43e67b64cddebb947d6
6141d45f67b64cddebb947dc
6141d4e267b64cddebb947e6
6141d57f67b64cddebb947f4


###
DELETE http://localhost:5000/api/posts/6141d57f67b64cddebb947f4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNlZDJlNzM4MDRhMTA4NmM4MTUzMmMiLCJpYXQiOjE2MzE3MDQ5MTh9.bxjJtCsuUnbTgK5Dnz9rZwaBBbnwPCeCbe63G9v2Bpw


###
GET http://localhost:5000/api/posts/find
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNlZDJlNzM4MDRhMTA4NmM4MTUzMmMiLCJpYXQiOjE2MzIwMzY1NDV9.gzAscjP3SBqRDTPbV4IewU2-QFTS45Z4PhWOPF5XnEY

{
    "title" : "Vue"
}


###
GET http://localhost:5000/api/posts/find
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNlZDJlNzM4MDRhMTA4NmM4MTUzMmMiLCJpYXQiOjE2MzIwMzY1NDV9.gzAscjP3SBqRDTPbV4IewU2-QFTS45Z4PhWOPF5XnEY

{
    "title" : "",
    "status" : "LEARNED"
}